### ISSUE TITLE
USA only accepts "US"

### ISSUE THREAD

**Issue by jbleyleSF** [arufian/LWC-Component-COVID19#2]
None of these values work: 

- USA
- United States
- United States of America

**Comment by arufian** [comment]
Hi @jbleyleSF 
I will add these as synonyms for "U.S" in the API

**Comment by arufian** [comment]
I have add synonyms system to the API.
Please look at this gif.
![Synonyms](https://user-images.githubusercontent.com/480889/78567986-71cff580-785c-11ea-98dc-266ec7142d79.gif)

I will close this and #4 issue.
