### ISSUE TITLE
Data doesn't reload when you change country name and save

### ISSUE THREAD

**Issue by jbleyleSF** [arufian/LWC-Component-COVID19#3]
1. Create Account with country Germany and Save. 
1. Change country to France and Save. 

Expected: 
Data from France loads

Actual:
France title loads, but data doesn't. 
Note that when I refresh the page, the data from France loads.

![Screen Shot 2020-04-02 at 11 04 03 AM](https://user-images.githubusercontent.com/32077211/78282811-be6ca700-74d1-11ea-9afa-1f371d126d01.png)

**Comment by arufian** [comment]
Hi @jbleyleSF 
I have investigated this issue, but the data loaded as expected.
Here is my screen recording as a proof:
![update-field](https://user-images.githubusercontent.com/480889/78563359-cd4ab500-7855-11ea-80df-6966307fdeef.gif)

**Comment by jbleyleSF** [comment]
After an error, you must reload the page to see the data again.
![2020-04-06_10-51-12](https://user-images.githubusercontent.com/32077211/78589394-fedf6400-77f4-11ea-9dc7-aeae7597cf21.gif)

**Comment by arufian** [comment]
It seems it's okay for you, I will close the issue
