### ISSUE TITLE
After an error, must reload page to see data

### ISSUE THREAD

**Issue by jbleyleSF** [arufian/LWC-Component-COVID19#5]
![2020-04-06_10-51-12](https://user-images.githubusercontent.com/32077211/78589604-52ea4880-77f5-11ea-8aad-4b67a3189c77.gif)

**Comment by arufian** [comment]
@jbleyleSF I will work on this by tonight

**Comment by arufian** [comment]
Hi @jbleyleSF 
I have fixed this issue, please checkout new source code on this repo or download the [1.0.1 version ](https://github.com/arufian/LWC-Component-COVID19/releases/tag/v1.0.1)release.
